Update article.md
javascript-tutorial/en.javascript.info pull request #1750
Opened 2020-02-13 18:31 UTC by galunni

precedence 17 instead of 16 now, since table has been updated

2020-02-13 18:32 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/en.javascript.info?pullRequest=1750) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/en.javascript.info?pullRequest=1750) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/en.javascript.info?pullRequest=1750) it.</sub>

2020-02-13 20:43 UTC, ghost requested changes

2020-04-29 08:57 UTC, iliakan commented
Sorry, was busy with other development for some time. Merging!

2020-04-29 08:57 UTC, merged

2026-08-07 06:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/en.javascript.info?pullRequest=1750) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/en.javascript.info?pullRequest=1750) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/en.javascript.info?pullRequest=1750) it.</sub>