Promise.any
javascript-tutorial/en.javascript.info pull request #2288
Opened 2020-11-17 04:58 UTC by lumosmind

I think `Promise.any()` must be in this article. It is very critical when we work with multiple source content.

2020-11-17 16:01 UTC, vsemozhetbyt commented on 1-js/11-async/05-promise-api/article.md
> +The first promise here was fastest, but it rejecets, so the second promise became the result. After the first fulfilled promise "wins the race", all further results are ignored.
```suggestion
The first promise here was fastest, but it was rejected, so the second promise became the result. After the first fulfilled promise "wins the race", all further results are ignored.
```

2020-11-25 05:59 UTC, iliakan requested changes
Please fix the example.
And maybe add it to the Summary section?

2020-11-25 05:59 UTC, iliakan commented on 1-js/11-async/05-promise-api/article.md
> +Promise.race([
Promise.race example here?

2020-11-25 19:50 UTC, lumosmind commented on 1-js/11-async/05-promise-api/article.md
> +Promise.race([
I did some changes to meet requirements

2020-11-29 07:56 UTC, iliakan commented
Thank you!

2020-11-29 07:56 UTC, merged