Rephrased for clarity.
javascript-tutorial/en.javascript.info pull request #2302
Opened 2020-11-19 15:15 UTC by patrikbego

2020-11-23 12:05 UTC, iliakan commented
Thanks. I'm not sure though, why "Set-like" is bad?

2020-11-23 12:05 UTC, iliakan commented
People say "Array-like", and that's normal.

2020-11-23 12:06 UTC, iliakan commented on 1-js/05-data-types/08-weakmap-weakset/article.md
> +Being "weak", it also serves as additional storage. But not for arbitrary data, but rather for "yes/no" facts. A membership in `WeakSet` may mean something about the object.
Please, remove one "But" here too =)

2020-11-23 12:06 UTC, iliakan requested changes
Please, remove one "But" where commented, and - are you sure that "set-like" is bad?

2020-11-24 22:35 UTC, patrikbego commented on 1-js/05-data-types/08-weakmap-weakset/article.md
> +Being "weak", it also serves as additional storage. But not for arbitrary data, but rather for "yes/no" facts. A membership in `WeakSet` may mean something about the object.
Yes, that is better ;)

2020-11-24 22:36 UTC, patrikbego commented
> Please, remove one "But" where commented, and - are you sure that "set-like" is bad?
You are right, it actually is dramatically correct. I put it back.

2020-11-29 08:24 UTC, iliakan commented
Thanks!

2020-11-29 08:25 UTC, merged